# Generated by Django 5.0.1 on 2024-02-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tempoInicio', models.DateField()),
                ('tempoFim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
